development:
  adapter: postgresql
  encoding: unicode
  database: noa_app_development_3
  pool: 5
  username: kellywaters 
  password: 

test:
  adapter: postgresql
  encoding: unicode
  database: noa_app_test_2
  pool: 5
  username: kellywaters
  password: 